# Generated by Django 4.0.5 on 2022-06-24 09:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 6, 24, 14, 50, 5, 938348)),
        ),
    ]
