# Generated by Django 4.0.5 on 2022-06-29 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_date_dailyreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 6, 29, 13, 9, 17, 593582)),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 6, 29, 13, 9, 17, 594580)),
        ),
    ]
