# Generated by Django 4.0.5 on 2022-06-30 11:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_attendance_date_alter_dailyreport_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 6, 30, 17, 28, 40, 11785)),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 6, 30, 17, 28, 40, 13793)),
        ),
    ]
