# Generated by Django 4.0.5 on 2022-06-30 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_alter_attendance_date_alter_dailyreport_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 6, 30, 17, 35, 55, 84440)),
        ),
        migrations.AlterField(
            model_name='dailyreport',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 6, 30, 17, 35, 55, 84440)),
        ),
    ]
