# Generated by Django 4.0.5 on 2022-07-04 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deploy_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 4, 19, 11, 30, 991396)),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 4, 19, 11, 30, 991396)),
        ),
    ]
