# Generated by Django 4.0.5 on 2022-07-04 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_deploy_date_alter_project_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='deploy_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 4, 19, 27, 50, 830704)),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 7, 4, 19, 27, 50, 830704)),
        ),
    ]
