# Generated by Django 4.0.5 on 2022-06-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=30)),
                ('company_name', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=15)),
                ('alt_contact_num', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=200)),
                ('project_category', models.CharField(max_length=100)),
                ('project', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('requirement_pdf', models.FileField(null=True, upload_to='')),
                ('reference', models.URLField(blank=True)),
            ],
        ),
    ]
