# Generated by Django 4.0.5 on 2022-06-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='requirement_pdf',
            field=models.FileField(null=True, upload_to='customer/images'),
        ),
    ]
