# Generated by Django 4.0.5 on 2022-06-22 11:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_rename_profile_employee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Profile',
        ),
    ]
