# Generated by Django 4.0.5 on 2022-06-22 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profile_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='category',
            field=models.CharField(choices=[('Developer', 'Developer'), ('HR', 'HR'), ('Project Manger', 'Project Manger'), ('Marketing Person', 'Marketing Person')], default='Developer', max_length=50),
        ),
    ]
