# Generated by Django 4.0.5 on 2022-06-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profile_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='category',
            field=models.CharField(choices=[('Developer', 'Developer'), ('HR', 'HR'), ('Project Manager', 'Project Manager'), ('Marketing Person', 'Marketing Person')], default='Developer', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='rewards',
            field=models.CharField(max_length=500),
        ),
    ]
