# Generated by Django 4.0.5 on 2022-07-25 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_profile_category_alter_profile_rewards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='category',
        ),
    ]
