# Generated by Django 4.0.5 on 2022-07-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_profile_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='category',
            field=models.CharField(choices=[('Developer', 'Developer'), ('HR', 'HR'), ('Project Manager', 'Project Manager'), ('Marketing Person', 'Marketing Person')], default='Developer', max_length=50),
        ),
    ]
